### ISSUE TITLE
¿Qué es un componente?

### ISSUE THREAD

**Issue by spmanolo** [DarckMonster/PCscrap#11]
Cuando hablamos de un componente en varias historias de usuario (por ejemplo en #3), nos referimos a un componente concreto de un ordenador. Por ejemplo, una tarjeta gráfica, una placa base, un procesador, una memoria RAM, un disco duro, etc. 

Estos componentes son únicos y tienen características que los diferencian de otros, por lo que la información que necesitamos en este caso es su nombre y tipo de componente del que se trata, además del umbral de precio:

- Nombre
- Tipo
- PrecioMinimo
- PrecioMaximo

**Comment by DarckMonster** [comment]
Bien, dado que los componentes simplemente se distinguen por su nombre y tipo (o categoría) no hace falta incluir más información para clasificarlos. Obviamente a la hora de hacer la clase además de esos atributos habría que poner el precio.

**Comment by spmanolo** [comment]
Lo he modificado para que también contenga el abanico de precio que se quiere pagar por el componente.
