### ISSUE TITLE
¿Cuáles son los tipos de componente?

### ISSUE THREAD

**Issue by spmanolo** [DarckMonster/PCscrap#12]
En #11 nos hemos referido a que un componente tiene que ser de un tipo, por lo que hay que definir que un componente de un ordenador pertenece a un tipo concreto de componente, por ejemplo: Una tarjeta gráfica RTX 4080 mencionada en #3 pertenece al tipo de componente de las **tarjetas gráficas**, o un procesador Intel i9 pertenece al tipo de componente de las **CPU**.

De esta forma podemos definir un enumerado que contenga los tipos de componente de un ordenador, para que nos ayude a clasificar mejor los componentes:

- CPU
- Tarjeta Gráfica

Ahora mismo con los datos que tenemos de las historias de usuario, ese enumerado nos podría servir para seguir avanzando, aunque posteriormente se podría ampliar con nuevos tipos de componentes.

**Comment by DarckMonster** [comment]
Ese listado de tipos de componentes es adecuado, ya que nos centramos en los componentes que suponen más gasto en un ordenador. Sin embargo, a la hora de buscar tanto RAM como discos duros se trata de algo más complejo. Cuando alguien busca RAM o un disco duro lo que busca más que un modelo en concreto como puede pasar con las tarjetas gráficas o las CPUs, busca un drive con una cantidad de memoria determinada y en los discos duros su velocidad. Para solucionar esto, en los nombres siempre ponen la capacidad del componente de forma que así podemos filtrar en el nombre. 

Esto último puede que sea algo para una fase más avanzada del proyecto, pero lo planteo para incluir o no los dos últimos tipos de componentes ya que puede que haga falta añadir más atributos dependiendo del tipo. 

En las historias de usuario 3 de las 4 piden tarjeta gráfica o precesador que suelen ser los componentes más caros del ordenador. Solo una HU no elige un componente en específico. Por eso podríamos especializarnos más en lugar de ir a por todos los componentes (o casi todos).

**Comment by spmanolo** [comment]
Tienes razón, he modificado el listado para que en principio solo contenga dos tipos de componentes (CPU y GPU), ya que como dices lo mejor va a ser especializarnos en lugar de abarcar todos los tipos de componentes.
