### ISSUE TITLE
¿Qué es el scraping?

### ISSUE THREAD

**Issue by spmanolo** [DarckMonster/PCscrap#13]
Es un proceso por el cual se mandan peticiones HTTP GET a una web y se analizan los resultados que se obtienen para encontrar una solución a un problema planteado. En nuesto caso se necesita conocer el precio de un componente en una tienda web, por lo que necesitaremos información del componente, la información de la tienda web a la que vamos a acceder, como puede ser su URL.
 
El resultado del scraping será analizado y filtrado para quedarnos con lo que buscamos, el precio del componente, que será almacenado.

**Comment by DarckMonster** [comment]
Correto. Como curiosidad, no lo pensé mucho y el proyecto se llama PCscrap aunque debería ser scrape. Pero ya se queda así,"Basura de PC" se va a quedar.

**Comment by spmanolo** [comment]
Bueno ojalá sea eso lo único por lo que tener que preocuparse :smile:

**Comment by JJ** [comment]
Este issue no hace referencia a ninguna historia de usuario. Como he comentado en [este comentario](https://github.com/DarckMonster/PCscrap/pull/9#discussion_r1376641903), eso lo hace inválido y por tanto también el código que se ha desarrollado.

**Comment by JJ** [comment]
Aparte, "¿Qué es X?" tampoco plantea un problema. Deberías expresar claramente qué problema hay en función de la lógica de negocio.
El código es solución a un problema, una respuesta al mismo. Responder a "¿Qué es el scraping?" con una clase que se llama `PcScrap` no parece que sea la respuesta más adecuada.
