### ISSUE TITLE
¿Cómo hacer scraping?

### ISSUE THREAD

**Issue by spmanolo** [DarckMonster/PCscrap#15]
En las historias de usuario #3, #4, #5 y #6 se menciona la idea de obtener un listado de precios en distintas webs, encontrar ofertas o recibir una recomendación sobre un componente, esto se trata de hacer scraping web: obtener información de una fuente de datos. En este caso para hacer esto vamos a necesitar información del `componente` que hay que buscar y un listado de tiendas web en las que buscar. Los resultados se almacenarán en un listado de precios.

- componente
- tiendas
- listado de precios

**Comment by DarckMonster** [comment]
Vale, me parece una buena forma de almacenar la información que sacamos de las páginas web. Una vez hecho el scraping tenemos cada componente con sus distintos precios por tienda. :smiley:

**Comment by spmanolo** [comment]
La idea de esta clase es almacenar los precios para un solo componente, ya que cada HU se basa en la búsqueda de un solo componente, he planteado esto así: tenemos un componente, un listado de tiendas donde buscar y como resultado un listado de precios de las distintas tiendas para ese componente

**Comment by DarckMonster** [comment]
Perfecto :+1:
