### ISSUE TITLE
El precio de un componente debería estar representado en Euros

### ISSUE THREAD

**Issue by spmanolo** [DarckMonster/PCscrap#16]
En #3 se menciona que se quiere encontrar un producto al mejor precio, pero no se especifica en qué unidad está el precio.
Puede haber incopatibilidades al haber usuarios que usen distintas monedas, por eso se debería unificar en una sola moneda.

**Comment by DarckMonster** [comment]
Perfecto 👍

**Comment by JJ** [comment]
Todos los issues deben incluir un enlace a la historia de usuario. Si no se hace así, el código que se haya desarrollado para este issue es incorrecto.
