### ISSUE TITLE
Elección del lenguaje de programación

### ISSUE THREAD

**Issue by spmanolo** [DarckMonster/PCscrap#17]
Hola @DarckMonster! ¿Que te parece `TypeScript` como lenguaje de programación para el proyecto?

**Comment by DarckMonster** [comment]
Hola! Pues es un lenguaje de programación interesante y del cual tenía muchas ganas de aprender. Y creo que es adecuado para hacer scraping.

Elegimos `TypeScript` como lenguaje de programación del proyecto.

**Comment by spmanolo** [comment]
Genial :+1:
