### ISSUE TITLE
¿Cómo se va a hacer scraping?

### ISSUE THREAD

**Issue by spmanolo** [DarckMonster/PCscrap#19]
En las historias de usuario #3, #4, #5 y #6 se menciona la idea de hacer scraping, si buscamos un tipo de componente en específico, por ejemplo como se menciona en #3, que se busca una tarjeta gráfica, necesitamos poder buscar en una página web estos componentes a través de una url específica, además de la información de un componente específico para buscarlo.

**Comment by DarckMonster** [comment]
Correcto, en el caso de las tarjetas gráficas todas se encuentran en una misma página web. Sin embargo esa página web no muestra todas, por lo que hay que pasar páginas dentro de la web para visualizarlas todas. Si se trata de una sola en concreto será más fácil.
