### ISSUE TITLE
¿Qué se entiende por página web?

### ISSUE THREAD

**Issue by spmanolo** [DarckMonster/PCscrap#20]
La página web será donde busquemos los precios de los componentes, pero para buscar un componente específico, no nos sirve solo con la URL base de la página, si no que habrá que encontrar que ruta nos lleva a una lista de componentes de un tipo específico. En #3 se busca una tarjeta gráfica concreta y se menciona PcComponentes como una página de confianza en la que buscar.

Además se necesita una forma de acceder a la información del componente dentro de la web, encontrando qué elementos del DOM las contienen.

**Comment by DarckMonster** [comment]
Sí, esa es la difucultad de la lógica de negocio.
