### ISSUE TITLE
¿Qué es un componente?

### ISSUE THREAD

**Issue by spmanolo** [DarckMonster/PCscrap#21]
Cuando hablamos de un componente en varias historias de usuario (por ejemplo en #3), nos referimos a un componente concreto de un ordenador. Por ejemplo, una tarjeta gráfica, una placa base, un procesador, una memoria RAM, un disco duro, etc.

Estos componentes son únicos y tienen características que los diferencian de otros.

**Comment by DarckMonster** [comment]
Correcto 👍
