### ISSUE TITLE
Selección del lenguaje para el proyecto

### ISSUE THREAD

**Issue by spmanolo** [DarckMonster/PCscrap#8]
Hola! Me ha tocado trabajar sobre tu proyecto. ¿Que te parece `TypeScript` como lenguaje de programación?

**Comment by DarckMonster** [comment]
Hola! Pues es un lenguaje de programación interesante y del cual tenía muchas ganas de aprender. Y creo que es adecuado con el proyecto. 

Genial, nos decidimos por `TypeScript`.

Saludos.

**Comment by spmanolo** [comment]
Genial!
